secretStore:
  enabled: false
  kind: "SecretStore"
  name: "aws-secrets-manager"
  region: ""

externalSecret:
  enabled: false
  secretStoreRefName: "fleet-eks-secret-store"
  secretStoreRefKind: "SecretStore"
  server: "spoke"
  fleet_member: "spoke"
  secretManagerSecretName: ""


gitSecrets:
  enabled: false
  secretStoreRefName: "fleet-eks-secret-store"
  secretStoreRefKind: "SecretStore"
  externalSecrets:
    addons:
      secretName: "git-addons"
      secretManagerSecretName: ""
    fleet:
      secretName: "git-fleet"
      secretManagerSecretName: ""
    platform:
      secretName: "git-platform"
      secretManagerSecretName: ""
    workloads:
      secretName: "git-workloads"
      secretManagerSecretName: ""
